name: CI

on:
  push:
    branches: ["main", "feat/*"]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: install dependency
        run: yarn
      - name: create dist path
        run: mkdir -p dist/v2
      - name: fix html loader
      # https://github.com/i18next/i18next-parser/commit/6a48bd460ede9f01decbf9f2e3bbaa70ee781d83
        run: sed -i '' 's|import cheerio from "cheerio";|import * as cheerio from '\''cheerio'\'';|'  node_modules/@esbuilder/html/lib/html.mjs
      - name: Create Firefox artifacts
        run: yarn build firefox
      - uses: actions/upload-artifact@v3
        with:
          name: read-later
          path: dist/v2/